BASE_TASK_CONFIG_PATH: "configs/replica/audiogoal.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 1000
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "test_unheard"
  USE_CKPT_CONFIG: True
